[package]
name = "clover_downloader"
version = "0.1.0"
authors = ["voloshink <voloshin.k@husky.neu.edu>"]

[dependencies]
clap = "2.32.0"
regex = "1.0.4"
reqwest = "0.8.8"
serde = "1.0.76"
serde_derive = "1.0.76"
serde_json = "1.0.26"